### ISSUE TITLE
Changing font of keyboard

### ISSUE THREAD

**Issue by rahthakor** [archagon/tasty-imitation-keyboard#105]
Hi,

I have tried to use keyboard as extension with Raleway Font(Google) but I'm not able to see displaying Raleway font on input control. It uses same system font.

Is it possible to do so to change font of textfield or textarea of any 3rd Party app.

Thanks in advance

Regards,
rAhul

**Comment by AaronFW** [comment]
I do not understand exactly what you are trying to do. Can you describe it in another way? 

Are you saying, you want to change the Output of the keyboard so that you can type Raleway Font into any textField?

**Comment by rahthakor** [comment]
I have created keyboard extension with reference to this repo.

What I have changed is system font to Raleway Font(Google) which are displayed on keyboard buttons without any problem. But When I press any button on keyboard that particular button title is display or textfield or wherever I'm typing but with system font not with font which I'm using in my keyboard title.

As you might know insertText method takes only string without any attributes so I can not tell system to render it in Raleway font. This scenario happens only when I'm using keyboard as extension not within host containing app.

I want o achieve something like this
fancy keyboard screenshot
![fancy keyboard screenshot](https://cloud.githubusercontent.com/assets/8470553/18774746/ddb02ab4-8179-11e6-9697-22ea4dc7b130.png)

This is fancy characters. I just want to change font style to another not available in system.

**Comment by polishedcode** [comment]
I don't think you can specify the font of the text being inserted into the
containing app. The keyboard in your picture is probably inserting a string
that is a combination of capital T plus some combining diacritics. If you
were to backspace in the containing app you would see that it takes
multiple backspaces to erase that sequence.

**Comment by rahthakor** [comment]
When I have search regarding this issues on google I came across BytaFont and Cydia but that is with jailbreak option.
Even though I have seen some of the keyboard apps are using a different font than a system without jailbreak which is making me crazy how they are doing it.

I also read about TextKit in detail for changing it from another layer. But couldn't get succeeded.

**Comment by Archivus** [comment]
@rahthakor @polishedcode this is not a font change but rather unicode symbols. i.e. see letter code symbols, enclosed alpha numerics etc. So instead of inserting a string in the keyboard method, insert a unicode symbol :)

**Comment by rahthakor** [comment]
Let me show you some app which I have seen they haven't used Unicode characters rather than they have just changed a font,  even not similar to other languages which have different strokes.

[Better Font app](https://itunes.apple.com/us/app/keyboard-skins-for-iphone/id935588678?mt=8)
And this also
[Keyboard Skins for iPhone and iPad](https://itunes.apple.com/us/app/better-fonts-free-now-cool/id735011588?mt=8)

They do have many fonts from which some of the fonts have different fonts which do not have Unicode characters.

**Comment by Archivus** [comment]
@polishedcode @rahthakor trust me, they're not changing the font. Just unicode modifiers. Insert this as the output for one of your keys 'ᴴᵉˡˡᵒ'. I haven't tested it but I'm positive it'll work. Those developers just market it as different fonts.

**Comment by AaronFW** [comment]
I downloaded Better Font, but most of the fonts are unicode. For example, the main pre-installed one is mostly Amharic characters mapped to an English keyboard. Others used random Cyrillic characters. I didn't find any that I didn't think were unicode. For example, here is the unicode for the [Enclosed Alphanumeric:](https://en.wikipedia.org/wiki/Enclosed_Alphanumerics) ⓧⓨⓩ⓪⓫⓬⓭ 

If you wanted to learn more about the libraries used in apps you could use something like dumpdecrypted. I don't have experience, but I thought[ this video](https://realm.io/news/conrad-kramer-reverse-engineering-ios-apps-lyft/?utm_source=facebook&utm_medium=cpc&utm_campaign=reverse-engineering) was helpful as a starting place to learn about tools to learn about how specific apps function.

**Comment by rahthakor** [comment]
@AaronFW I just watch that video that might help but that too much work to do for it.
anyways thanks for the link.
back to original question. I still think that there much be something available which is not documented by any of trusted resources.
Because I have tried really hard to get any idea about how this is posible at all.

Only thing I can pass while entering something from keyboard is unattributed string. Apart from that I can not really pass anything. I can manage to work with any unicode available but still have no idea on how diacritics.

**Comment by AaronFW** [comment]
The reason I am still skeptical about the possibility of outputting a font into a textField is because the font is usually determined by the textField itself. The default for textFields is to rely on the UserDefault font but you can set a FontFamily manually. I don't know anything about changing font's programmatically or making a UIButton to do so, that hasn't been something I've needed to learn. Using a new font adds the difficulty of installing the font to be recognized by the iOS device with the added difficulty that others on the receiving end of the message would not see the font if it is not installed on their device. (I assume that iOS changes replaces unrecognized fonts with the UserDefault Font because some Font must be presented at all costs. It is likely some condition that checks fonts against the list of installed fonts, and if it is not in the list, it replaces it with the UserDefault Font.) 

I haven't spent time to learn about how to pass gifs or pngs, so I cannot help you there. 

However, the keyboard I created uses a large number of diacritics (the same found in French: circumflex, grave, et cetera), what do you mean regarding "I can manage to work with any Unicode available but still have no idea how diacritics"?

**Comment by rahthakor** [comment]
@AaronFW After looking support from apple also, I got to know that what I'm looking for can not be implemented in iOS. Programmatically fonts can not be changed from another apps i.e keyboard extension. As you rightly mentioned about for font that It is determined by TextField not Keyboard button from another app.

I was presuming something different as a meaning of diacritics. I got it correctly now.

Very thanks for all the support to all contributor.

**Comment by prateekdroid08** [comment]
@rahthakor I am facing the same issue. Did you achieve the font in textfield ?
Waiting for your response.

**Comment by rahthakor** [comment]
@prateekdroid08 Unfortunately it is not possible in iOS.
It is not possible to develop a keyboard extension which changes font in different apps.

Just think of a scenario where you're writing something in slack and they use different fonts in their textfield according to their style guide and out of no where our app extension changes those input fonts.
