### ISSUE TITLE
Incompatible with Swift 3.0+/Xcode 8.3

### ISSUE THREAD

**Issue by rcedwards** [archagon/tasty-imitation-keyboard#115]
Creating an issue to track updating to Swift 3.0+.

There appears to be multiple open PRs addressing this. #114 #110 #111

**Comment by jams032** [comment]
I am facing 11 separate issue on xcode 8.3.2, swift 3.0
1. Catboard.swift , line 50,56- Editor placholder issue
2. ForwardingView.swift , line- 214 initialiser for conditional binding must have an optional type ,..... 
3. KeyboardViewController.swift , line483, 488, 493 - editor placholder issue.

**Comment by vccabral** [comment]
I am getting the same issues. @jams032 are you working on an update?  Is there a PR for this? Maybe we can get a group together to update for swift 3.0.

**Comment by AaronFW** [comment]
You might try looking at Polishedcode's version of the Tasty-Imitation-Keyboard and see how he handled those sections in his code. https://github.com/polishedcode/tasty-imitation-keyboard 

Alternatively, you could look at how I handled it in mine. Mine is based on Archagon's Swift 2.0 and I used a lot of Polishedcode's added functionality for my own project. Though, I do still have some cleaning up in my code to do, but you should be able to find the same .swift files and functions pretty easily to see how we migrated. 
https://github.com/AaronFW/Kouri-Vini

I'm not actively working on the Keyboard project or with Swift, so I cannot give direct feedback to the issues mentioned.

**Comment by archagon** [comment]
PR merged.
