### ISSUE TITLE
Change language dynamically

### ISSUE THREAD

**Issue by thanospapazoglou** [archagon/tasty-imitation-keyboard#123]
Is it possible to change the language and the keyboard layout when a specific key is pressed?

**Comment by kamalupasena** [comment]
its possible in,(This is what i did)First create a function that return a keyboard with the keys of your selected language (See the implementation of the `DefaultKeyboard` class )  and then  go to the class   `KeyboardViewController` there is a function called `layoutHelper` using this u can changed the language of the keyboard very easily. you just have to return the keyboard you have created there. and when you click on your specific keyboard just reboot the keyboard and the rest will be done properly
