### ISSUE TITLE
Implementing keyboard in-app

### ISSUE THREAD

**Issue by 1fr0st** [archagon/tasty-imitation-keyboard#135]
Hello , I have a question.
Is there a way to implement this keyboard in an external app so I can use it with textFields?
I tried to use as textField.inputView but it gives me an error since inputView needs a UIView as parameter but KeyboardViewController is an UIInputViewController.
Thanks in advance!

**Comment by jeremymarch** [comment]
This works for me:
var kb: Catboard? = nil //or whatever your subclass of KeyboardViewController is

override func viewDidLoad() {
        super.viewDidLoad()
        kb = Catboard()
        kb?.inputView?.translatesAutoresizingMaskIntoConstraints = false
        textView!.inputView = kb?.inputView
}

**Comment by 1fr0st** [comment]
@jeremymarch  Really thank you!!!! it works
