### ISSUE TITLE
Keyboard doesn`t show up on messages app.

### ISSUE THREAD

**Issue by pirrate** [archagon/tasty-imitation-keyboard#25]
For some reason custom keyboard is not on the keyboard list when you hold globe button on Messages app. Any idea why?

**Comment by Amidos** [comment]
Eziz dostlar!

Eger menden size ingilis dilinde email gelibse onu achmayin. Spamdir! Eger
achib pdf download etmeye qeder getmisinizse tecili email shifrenizi
(linkedIn istifade edirisnizse onun da shifresini) deyishib!

Hormetle,
Amid

Dear Friends!

if you received and e-mail with English context from me please do not open
and just remove. This is a spam. if you already opened and clicked link
there and downloaded pdf please immediately change your e-mail password. If
u use linkedIn please change password of it too.

Sorry for inconvenience!

Regards,
Amid
