### ISSUE TITLE
Word prediction 

### ISSUE THREAD

**Issue by roohi66** [archagon/tasty-imitation-keyboard#65]
Thanks for this great project
I think space on top of keyboard is useless and it would be great to use it for something.
Can you set word prediction (like apple keyboard) on priority ?

**Comment by SchSimon** [comment]
That would be super cool!

**Comment by jermiy** [comment]
Bbcr did

**Comment by Archivus** [comment]
I second this :) I'll try and add it myself if possible and submit a pull request

**Comment by archagon** [comment]
As nice as this would be to have, I just don't have the time to put it in. Sorry!
