### ISSUE TITLE
Move settings section from keyboard to whole application

### ISSUE THREAD

**Issue by roohi66** [archagon/tasty-imitation-keyboard#69]
is there any way to move settings section to main application ?

(i tried to use NSUserDefaults but it seems keyboard part and application is completely separated and it did't any connection between them )

**Comment by laud** [comment]
You will need to enable App Groups for your application to share data via NSUserDefaults. Read more about it here: https://developer.apple.com/library/prerelease/ios/documentation/General/Conceptual/ExtensibilityPG/ExtensionScenarios.html

**Comment by roohi66** [comment]
thank you 
you saved my life

**Comment by archagon** [comment]
PS this will also require your users to enable Full Access, which will lead to annoyed users and bad reviews. It's why I chose to do it in-keyboard.

**Comment by pirrate** [comment]
using group id  doesn`t require Full Access. I am using it in my app and it works good.

**Comment by archagon** [comment]
That can't be right. My understanding is that it's impossible to share any data at all between a keyboard and the host app if Full Access is disabled. (Otherwise, a malicious keyboard could record a user's keystrokes, transmit them through the settings key/value store, and send them over the network when the host app is opened.) If you're able to share data between your keyboard and host app, are you sure your full access switch is off?

**Comment by pirrate** [comment]
I am turning Full Access ON only for keyboard sound purpose. In other cases group-id works just fine even if full access is off. This is part of my code

    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: NSBundle?) {
        let prefs = NSUserDefaults(suiteName: "group.net.my.id")
        
        
        if prefs!.objectForKey(kSmallLowercase) != nil
        {
            NSUserDefaults.standardUserDefaults().registerDefaults([
                kSmallLowercase: prefs!.boolForKey(kSmallLowercase),
                kAutoCapitalization: prefs!.boolForKey(kAutoCapitalization),
                kPeriodShortcut: prefs!.boolForKey(kPeriodShortcut),
                kKeyboardClicks: prefs!.boolForKey(kKeyboardClicks)
                ])
        }
        else {
            
            NSUserDefaults.standardUserDefaults().registerDefaults([
                kSmallLowercase: false,
                kAutoCapitalization: true,
                kPeriodShortcut: true,
                kKeyboardClicks: true
                ])
            
        }

**Comment by archagon** [comment]
Hmmmmmm interesting if true. Will need to investigate...

Many 3rd party keyboards I've seen also do in-keyboard settings to avoid the Full Access hurdle. Maybe something changed, or my understanding was wrong? Is it really the case that if you have Full Access off and toggle one of the settings in your app, you can detect the change in your keyboard?

**Comment by pirrate** [comment]
Yes man, i can 100% guaranty it! I am using it in my app and i have tested it in simulator and real device.  I have several switch in my container app. when i toggle any of them keyboard can understand it using group id-s and fullaccess if off.

**Comment by archagon** [comment]
Crazypants. Ok, maybe I will move settings out of the keyboard if it works, at least as an option. Don't wanna waste that space after all.

**Comment by pirrate** [comment]
That would be nice.

**Comment by tkersey** [comment]
I have to disagree with @pirrate. In my experience, you can get by with full access off (for NSUserDefaults) when running attached to Xcode in the simulator or on a real device but when you try to distribute (either through Apple's TestFlight or something like Crashlytics) it will not work (I'm guessing because of code signing). You have to enable App Groups to share NSUserDefaults between the extension and the hosting app when you are distributing an app.

**Comment by pirrate** [comment]
By the "group-id" in my previous comments i was meaning App Grups. And yes you have to enable it from Capabilities tab of Container app and Keyboard extension and request/register app group in your appstore account. If you do so it works perfect and you can access your preferences that you set in Container app from keyboard extension.

**Comment by tkersey** [comment]
@pirrate Have you tested this on a device without installing it from Xcode by using TestFlight, Crashlyiics, HockeyApp, etc?

**Comment by pirrate** [comment]
I have tested it with TestFlight. It works! i give you my word :)

**Comment by tkersey** [comment]
@pirrate Using a TestFlight build turn "Full Access" off and toggle a setting in the hosting app. Then confirm that in the keyboard. I'll bet that you will find that is does not work.

**Comment by pirrate** [comment]
i have to apologies guys. seems like testing on simulator and xcode build pushed me to wrong decision. Seems like it doesn`t work with TestFlight build. Sorry for wrong information!

**Comment by tkersey** [comment]
@pirrate I'm sort of glad that you were able to confirm. Hopefully you won't have to change to much. It's better to have learned this now than than after you've submitted to the App Store. :smile:

**Comment by pirrate** [comment]
@tkersey thanks for pushing me to test it carefully! :)

**Comment by archagon** [comment]
Phew, you almost shattered my entire world view. 😅

**Comment by pirrate** [comment]
heheh ))) Sorry man. I was testing it mainly in simulator or run in real device with xcode. Testing with TestFlight proved me that i am wrong.
