### ISSUE TITLE
How to set a custom font to be used across all of the iOS apps, like FancyKey?

### ISSUE THREAD

**Issue by waelsaad** [archagon/tasty-imitation-keyboard#73]
Hi,

I can modify the keyboard to have a completely different characters however when I click a key to insert one of the characters from my custom font, it shows as a question mark.

Unicode is not supported for this font and I am hoping that it is possible to do it as long as I have my font linked within the app.

self.label.font = UIFont (name: "Jinkim", size: 30) !. I am really hoping for some assistance.

I think FancyKey does this but I am not sure.

Thank you.

**Comment by waelsaad** [comment]
any response ?

**Comment by archagon** [comment]
So, you want your custom font as an output, not just for your key caps? If so, then it's impossible — sorry. The character insertion method is the only way to enter text into a text field, and it takes a simple string. Other keyboards simulate "fonts" by picking weird characters that resemble Latin letters from Unicode.

**Comment by waelsaad** [comment]
Thanks for response. This is really annoying and a huge limitation in iOS for languages that still don't have Unicode support such as the Coptic language I had to create "Coptic Notes" a complete Notes App and the iOS keyboard in order to support the Ancient Egyptian Coptic language. Thanks anyway.
