### ISSUE TITLE
Is there any option to resize "return" key's width ?

### ISSUE THREAD

**Issue by athimannil** [archagon/tasty-imitation-keyboard#74]
The custom keyboard is really awesome :+1: As a beginner it is really useful for me
I need to resize "return" key's width while developing the keyboard. Is there any option for that ?

![img_0460](https://cloud.githubusercontent.com/assets/4364227/6639955/11fa9a1c-c9ba-11e4-9826-851e181f6337.jpg)

**Comment by archagon** [comment]
Yeah, it should be pretty easy. The last row is laid out in the [`layoutSpecialKeysRow` function of `KeyboardLayout.swift`](https://github.com/archagon/tasty-imitation-keyboard/blob/master/Keyboard/KeyboardLayout.swift#L934). I believe the return key size is dictated by the `lastRowLandscapeLastButtonAreaWidthToKeyboardAreaWidth` and `lastRowPortraitLastButtonAreaWidthToKeyboardAreaWidth` constants, which are percentages of the keyboard width.
