### ISSUE TITLE
NSLayoutConstraint unable to simultaneously satisfy constraints.

### ISSUE THREAD

**Issue by bobintornado** [archagon/tasty-imitation-keyboard#85]
Hey all, I am getting the following warning when I launch the keyboard, anyone has experienced similar issue before? 

Keyboard[40697:2587035] Unable to simultaneously satisfy constraints.

Probably at least one of the constraints in the following list is one you don't want. Try this: (1) look at each constraint and try to figure out which you don't expect; (2) find the code that added the unwanted constraint or constraints and fix it. (Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 

(
    "\<NSLayoutConstraint:0x600000088110 V:[UIInputView:0x7ff78350d460(246)]\>",
    "\<NSLayoutConstraint:0x600000087d50 'UIView-Encapsulated-Layout-Height' V:[UIInputView:0x7ff78350d460(216)]\>"
)

Will attempt to recover by breaking constraint 
\<NSLayoutConstraint:0x600000088110 V:[UIInputView:0x7ff78350d460(246)]\>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.

**Comment by archagon** [comment]
Yeah, that error happens when you change the size of the keyboard. I don't think there's a way around it. (At least there wasn't one when I first implemented it.)

**Comment by bobintornado** [comment]
Is there a way "not to change it"? As how could we use the default height?
