### ISSUE TITLE
Remove settings and globe keys

### ISSUE THREAD

**Issue by cvonlehe** [archagon/tasty-imitation-keyboard#99]
Hey,

I just want to remove the settings and globe keys. What's the best way to go about doing this?

**Comment by AaronFW** [comment]
In DefaultKeyboard.swift, comment out the two lines near line 130 which relate to the keyboard change button and the settings button so that it should look like this
```
 // defaultKeyboard.addKey(Key(keyboardChange), row: 3, page: 2)  
//    defaultKeyboard.addKey(Key(settings), row: 3, page: 2)
```

However, if you were to publish a keyboard-app, be aware that Apple requires you to have key to change Keyboards.

**Comment by cvonlehe** [comment]
Great. Thank you for the quick response.
